name: Docs CI

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yaml'
  release:
    types:
      - published

jobs:
  docs:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      #----------------------------------------------
      # checkout repo & set up python
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      #----------------------------------------------
      # install & configure poetry
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install pandoc
      #----------------------------------------------
      - name: Install Pandoc
        run: |
          sudo apt-get install -y --no-install-recommends pandoc
      #----------------------------------------------
      # load cached venv
      #----------------------------------------------
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      #----------------------------------------------
      # install project
      #----------------------------------------------
      - name: Install project
        run: poetry install --no-interaction --with=docs
      #----------------------------------------------
      # build docs
      #----------------------------------------------
      - name: Build docs
        run: cd docs && make html
      #----------------------------------------------
      # publish docs to github pages
      #----------------------------------------------
      - name: Publish to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
