name: Release CI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build_and_release:
  #----------------------------------------------
  # Notes:
  #  in order to trigger the 'docs' action when
  #  the release is published, we must use a personal
  #  access token (PAT), instead of secrets.GITHUB_TOKEN
  #----------------------------------------------
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      #----------------------------------------------
      # checkout repo & set up python
      #----------------------------------------------
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      #----------------------------------------------
      # setup python
      #----------------------------------------------
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      #----------------------------------------------
      # load poetry, if cached
      #----------------------------------------------
      - name: Load cached Poetry
        id: cached-poetry-installation
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-cache-${{ runner.os }}-${{ env.POETRY_VERSION }}
      #----------------------------------------------
      # install poetry, if not cached
      #----------------------------------------------
      - name: Install Poetry
        if: steps.cached-poetry-installation.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      #----------------------------------------------
      # install project
      #----------------------------------------------
      - name: Install project
        run: poetry install --no-interaction
      #----------------------------------------------
      # build project
      #----------------------------------------------
      - name: Build project
        run: poetry build
      #----------------------------------------------
      # release project
      #----------------------------------------------
      - name: incremental CHANGELOG.md
        run: |
          sed -n "/^## ${{  github.ref_name }} .*$/,/^## /p" CHANGELOG.md | sed '$d' > incremental_changelog.txt
          cat incremental_changelog.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: ./dist/**
          body_path: incremental_changelog.txt
          token: ${{ secrets.PAT }}
